### ISSUE TITLE
TODO list for WorldReverter script

### ISSUE THREAD

**Issue by chalkpe** [if-Team/ModPE-Scripts#12]
- [ ] 블럭을 설치하거나 부수었을때 그 정보를 배열에 저장 (배열의 길이는 100이며 그 길이를 넘어서면 가장 오래된 정보를 삭제)
- [ ] 리스트 저장방식은 여러가지 (ex - 블럭단위,시간단위,같은 블럭단위...)
- [ ] 우측 하단의 버튼을 누르면 플레이어에게 리스트가 보여짐
- [ ] 플레이어가 리스트중 어느 한 곳을 선택하였을때 그 시점으로 블럭정보가 되돌아감(그 이후의 배열에 저장된 정보의 반대를 실행하는 방식(?))
- [ ] 롤백을 하였을때 그 이후의 배열에 저장된 정보는 삭제 후 다른 배열에 저장 (되돌리기에 이용)

**Comment by Hanarin** [comment]
호오
